### ISSUE TITLE
A Coding Question

### ISSUE THREAD

**Issue by WTriumphYMY** [jeffersonmsb/rocket-cooling-calculator#1]
In your pyCEA.py, line 212 and line 213, you coding like this
`if os.path.isfile(filename):
         return`
this will make program jump  function runCEA(filename) and will not generate .out file, i don't know why you write that

**Comment by jeffbzrr** [comment]
Hello, On the first run lots and lots of .out files are created.

On a second run the .out file for these properties may have already been created. So it's interesting not to create these files again. That way the execution time will be faster.

If you have any questions please feel free to ask.

**Comment by WTriumphYMY** [comment]
I find that your program is running on linux, but i need to run it windows, so some command line need to be modified, after finish that maybe i have more questions( ͡° ͜ʖ ͡°)✧ by the way may i have your email?ヾ(´∀｀。ヾ)

**Comment by jeffbzrr** [comment]
Yes, the program runs on Linux. I've never run on Windows, but I don't think it's a problem. However, it is necessary to install GFortran for Windows and modify some Linux for Windows format path.

You can have my email. It's jeffersonmsb@gmail.com

I'm happy to help.
